PluginClassName.config=Config
PluginClassName.invalidId=Invalid ID
PluginClassName.readonly=Readonly
PluginClassName.showActionsOnReadonly=Show actions on readonly
PluginClassName.datalistUrl=Datalist URL
PluginClassName.parameters=Parameters
PluginClassName.paramName=Parameter Name
PluginClassName.paramValue=Parameter Value
PluginClassName.paramSecondValue=Parameter Second Value
PluginClassName.paramSecondValueDescription=Parameter Second Value Description
PluginClassName.blurOverlay=Blur Overlay
